### ISSUE TITLE
Simulate tennis ball detection

### ISSUE THREAD

**Issue by c2huc2hu** [rsx-utoronto/simulation#1]
Create a tennis ball object in the simulation environment. Draw the tennis ball on the grid

Create an API endpoint `/drive/tennis-ball` that will return the angle that a tennis ball is detected at.

**Comment by marius343** [comment]
Overview of how the project would fit in with the rest of the rover:
- Simulating tennis ball detection would allow the autonomy team to develop their program in the winter, without having to test it on the actual rover

Goals of the project:
- To provide a realistic simulation environment that accurately models the real-world tennis ball challenge

Requirements that must be met with the project:
- Calls to server must be updated to match new API endpoints
- Rover movement and detection should be updated to be more accurate
- Tennis ball should be drawn and collision detection updated
